apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: 1c-apis
  description: A collection of 1C APIs
spec:
  targets:
    - ./apis/Edo-SendToEdo.yaml
    - ./apis/EdoSbis-ResponsiblePersons.yaml
