apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edo
  description: "Электронный документооборот"
  tags:
    - 1c
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
  annotations:
    backstage.io/source-template: template:default/springboot-template
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: 1c
  lifecycle: production
  owner: user:Тарасевич Роман
  system: 1cfinance
  providesApis: 
    - edo-api

  
