apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Technolog
  description: "Технологи и проверка качества"
  tags:
    - 1c
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
  annotations:
    backstage.io/source-template: template:default/springboot-template
    backstage.io/linguist: 'https://github.com/backstage/backstage/tree/master/plugins/playlist'
spec:
  type: 1c
  lifecycle: production
  owner: user:Тарасевич Роман
  consumesApis: 
    - edo-api
    - EdoSbis-ResponsiblePersons
